repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        description: Check Python fmt.
        entry: make fmt-check
        language: system
        types: [python]
        files: pyproject\.toml|\.py$
        pass_file_names: false
      - id: lint
        name: lint
        description: Run Python lints.
        entry: make lint
        language: system
        types: [python]
        files: pyproject\.toml|\.py$
        pass_file_names: false