repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        description: Check Python fmt.
        entry: make fmt-check
        language: system
        types: [python]
        files: pyproject\.toml|\.py$
        pass_filenames: false
      - id: flake8
        name: flake8
        description: Run Python lints.
        entry: make lint
        language: system
        types: [python]
        files: pyproject\.toml|\.py$
        pass_filenames: false
      - id: mypy
        name: mypy
        description: Check Python types.
        entry: make lint-types
        language: system
        types: [python]
        files: pyproject\.toml|\.py$
        pass_filenames: false
      - id: pytest
        name: pytest
        description: Run Python tests.
        entry: make test
        language: system
        types: [python]
        files: pyproject\.toml|\.py$
        pass_filenames: false